#!/bin/sh

. /scripts/lib.sh

ROOT_PASSWORD_HASH="$1"
ROOT_HOST="$2"

ESCAPE_ROOT_PASSWORD_HASH=`escape_name "${ROOT_PASSWORD_HASH}"`
ESCAPE_ROOT_HOST=`escape_name "${ROOT_HOST}"`

cat << EOF >> /scripts/mysqlrc
CREATE USER IF NOT EXISTS 'root'@'${ESCAPE_ROOT_HOST}';
ALTER USER 'root'@'${ESCAPE_ROOT_HOST}' IDENTIFIED BY PASSWORD '${ESCAPE_ROOT_PASSWORD_HASH}';
GRANT ALL ON *.* TO 'root'@'${ESCAPE_ROOT_HOST}' WITH GRANT OPTION;
EOF
